### ISSUE TITLE
RTD LaTeX broken?

### ISSUE THREAD

**Issue by IanHawke** [harpolea/r3d2#6]
Looking at http://r3d2.readthedocs.io/en/latest/states.html the LaTeX output appears wrong, and looking at http://r3d2.readthedocs.io/en/latest/riemann_problem.html it seems that the png output has taken priority over the LaTeX output. I wonder if there's some underlying changes from Jupyter?

**Comment by harpolea** [comment]
I get the same errors when I build locally, so quite possibly. I'll look into it.

**Comment by harpolea** [comment]
The equations might be a mathjax thing - the latex in the source looked fine. Switching the $'s to \begin{equation} and \end{equation} seemed to fix it though.

**Comment by IanHawke** [comment]
That's an interesting/odd change: I'm fairly certain I changed all the \begin{equation} etc blocks to $'s at one point precisely to fix a different sphinx or nbconvert problem.

However, I'm still see the png output rather than the LaTeX output on http://r3d2.readthedocs.io/en/latest/riemann_problem.html? ? Eg output [3] should be LaTeX. Is this just me?

**Comment by harpolea** [comment]
No, that's still broken for me too - puzzlingly, it still displays the png even if I tell nbsphinx not to execute the notebooks when it builds.

**Comment by harpolea** [comment]
It works if I get rid of the svg representation - do we need it in there?

**Comment by IanHawke** [comment]
Probably not: I put it in as svg->pdf should give cleaner figures for
publications, but in reality the auto-figures aren't going to go in any
paper, I expect, so the svg can go.

**Comment by harpolea** [comment]
Fixed with https://github.com/harpolea/r3d2/commit/44e93160a2acd9f8ab44b0a2d2a20842481dec36
